name: test

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Test
        run: mvn -B clean install --file pom.xml

      - name: Checkout n5-universe Repository
        uses: actions/checkout@v2
        with:
          repository: <username>/n5-universe
          path: n5-universe

      - name: Get version from Maven and Replace
        run: |
          version=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
          sed -i "s|<n5-aws-s3.version>.*</n5-aws-s3.version>|<n5-aws-s3.version>$version</n5-aws-s3.version>|g" n5-universe/pom.xml

      - name: Maven Test Against N5-Universe
        run: mvn -B clean test --file n5-universe/pom.xml
