name: test

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Test
        run: mvn -B clean install --file pom.xml

      - name: Checkout n5-universe Repository
        uses: actions/checkout@v2
        with:
          repository: saalfeldlab/n5-universe
          path: n5-universe


      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install blosc (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pip install blosc --no-input --target n5-universe/src/test/resources
          mv n5-universe/src/test/resources/bin/* n5-universe/src/test/resources
      - name: Install blosc (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install blosc --no-input --target n5-universe/src/test/resources
          mv n5-universe/src/test/resources/lib64/* n5-universe/src/test/resources

      - name: Get version from Maven and Replace
        run: |
          version=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
          sed -i "s|<n5-aws-s3.version>.*</n5-aws-s3.version>|<n5-aws-s3.version>$version</n5-aws-s3.version>|g" n5-universe/pom.xml

      - name: Maven Test Against N5-Universe
        run: mvn -B clean test --file n5-universe/pom.xml
